name: antideepfake
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - expat=2.7.1
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - ncurses=6.5
  - openssl=3.0.17
  - pip=25.1
  - pthread-stubs=0.3
  - python=3.10.18
  - readline=8.2
  - setuptools=78.1.1
  - sqlite=3.50.2
  - tk=8.6.14
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - absl-py==2.3.1
      - certifi==2025.8.3
      - charset-normalizer==3.4.2
      - contourpy==1.3.2
      - cycler==0.12.1
      - filelock==3.13.1
      - fonttools==4.59.0
      - fsspec==2024.6.1
      - grpcio==1.74.0
      - hf-xet==1.1.5
      - huggingface-hub==0.34.3
      - idna==3.10
      - jinja2==3.1.4
      - joblib==1.5.1
      - kiwisolver==1.4.8
      - markdown==3.8.2
      - markupsafe==2.1.5
      - matplotlib==3.10.5
      - mpmath==1.3.0
      - networkx==3.3
      - numpy==2.1.2
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - packaging==25.0
      - pandas==2.3.1
      - pillow==11.0.0
      - protobuf==6.31.1
      - pyparsing==3.2.3
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.2
      - regex==2025.7.34
      - requests==2.32.4
      - safetensors==0.5.3
      - scikit-learn==1.7.1
      - scipy==1.15.3
      - seaborn==0.13.2
      - six==1.17.0
      - sympy==1.13.1
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - threadpoolctl==3.6.0
      - tokenizers==0.21.4
      - torch==2.6.0+cu124
      - torchaudio==2.6.0+cu124
      - torchvision==0.21.0+cu124
      - tqdm==4.67.1
      - transformers==4.54.1
      - triton==3.2.0
      - typing-extensions==4.12.2
      - tzdata==2025.2
      - urllib3==2.5.0
      - werkzeug==3.1.3
